FROM alpine:3.3
RUN apk add --no-cache mysql-client
RUN apk add --no-cache git
RUN apk add --no-cache python3
RUN git clone https://github.com/gutowsmi/YaDBs
ADD crontab.txt /crontab.txt
ADD script.sh /script.sh
COPY entry.sh /entry.sh
RUN chmod 755 /script.sh /entry.sh
RUN /usr/bin/crontab /crontab.txt

CMD ["/entry.sh"]